# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gameroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('label', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.TextField()),
                ('user_one', models.TextField()),
                ('user_two', models.TextField(blank=True, null=True)),
                ('player_one', models.TextField()),
                ('player_two', models.TextField(blank=True, null=True)),
                ('user_one_score', models.IntegerField(default=0)),
                ('user_two_score', models.IntegerField(default=0)),
                ('max_cards', models.IntegerField()),
                ('type_of_game', models.TextField()),
                ('player_one_turn', models.BooleanField()),
                ('player_two_turn', models.BooleanField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('Gameroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Room.Gameroom')),
            ],
        ),
    ]
