# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='player_one',
            field=models.TextField(blank=True, null=True),
        ),
    ]
