# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('team', models.CharField(blank=True, max_length=15, null=True)),
                ('playing_role', models.CharField(blank=True, max_length=20, null=True)),
                ('one_day_matches', models.IntegerField(blank=True, null=True)),
                ('one_day_not_outs', models.IntegerField(blank=True, null=True)),
                ('one_day_runs', models.IntegerField(blank=True, null=True)),
                ('one_day_highest_score', models.IntegerField(blank=True, null=True)),
                ('one_day_bat_average', models.FloatField(blank=True, null=True)),
                ('one_day_bat_str_rate', models.FloatField(blank=True, null=True)),
                ('one_day_hundreds', models.IntegerField(blank=True, null=True)),
                ('one_day_fifties', models.IntegerField(blank=True, null=True)),
                ('one_day_fours', models.IntegerField(blank=True, null=True)),
                ('one_day_sixes', models.IntegerField(blank=True, null=True)),
                ('one_day_balls', models.IntegerField(blank=True, null=True)),
                ('one_day_runs_against', models.IntegerField(blank=True, null=True)),
                ('one_day_wickets', models.IntegerField(blank=True, null=True)),
                ('one_day_bbm_wkts', models.IntegerField(blank=True, null=True)),
                ('one_day_bbm_runs', models.IntegerField(blank=True, null=True)),
                ('one_day_bowl_average', models.FloatField(blank=True, null=True)),
                ('one_day_econ_rate', models.FloatField(blank=True, null=True)),
                ('one_day_bowl_str_rate', models.FloatField(blank=True, null=True)),
                ('one_day_no_of_five_wickets', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'one_day',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('team', models.CharField(blank=True, max_length=15, null=True)),
                ('playing_role', models.CharField(blank=True, max_length=20, null=True)),
                ('test_matches', models.IntegerField(blank=True, null=True)),
                ('test_not_outs', models.IntegerField(blank=True, null=True)),
                ('test_runs', models.IntegerField(blank=True, null=True)),
                ('test_highest_score', models.IntegerField(blank=True, null=True)),
                ('test_bat_average', models.FloatField(blank=True, null=True)),
                ('test_bat_str_rate', models.FloatField(blank=True, null=True)),
                ('test_hundreds', models.IntegerField(blank=True, null=True)),
                ('test_fifties', models.IntegerField(blank=True, null=True)),
                ('test_fours', models.IntegerField(blank=True, null=True)),
                ('test_sixes', models.IntegerField(blank=True, null=True)),
                ('test_balls', models.IntegerField(blank=True, null=True)),
                ('test_runs_against', models.IntegerField(blank=True, null=True)),
                ('test_wickets', models.IntegerField(blank=True, null=True)),
                ('test_bbi_wkts', models.IntegerField(blank=True, null=True)),
                ('test_bbi_runs', models.IntegerField(blank=True, null=True)),
                ('test_bbm_wkts', models.IntegerField(blank=True, null=True)),
                ('test_bbm_runs', models.IntegerField(blank=True, null=True)),
                ('test_bowl_average', models.FloatField(blank=True, null=True)),
                ('test_econ_rate', models.FloatField(blank=True, null=True)),
                ('test_bowl_str_rate', models.FloatField(blank=True, null=True)),
                ('test_no_of_five_wickets', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'tests',
            },
        ),
    ]
