# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.CharField(max_length=50)),
                ('player1_name', models.CharField(max_length=50)),
                ('player2_name', models.CharField(max_length=50)),
                ('games', models.CharField(max_length=50)),
                ('player1_score', models.IntegerField(blank=True, null=True)),
                ('player2_score', models.IntegerField(blank=True, null=True)),
                ('order_of_play', models.BooleanField()),
            ],
        ),
    ]
