# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards_db', '0002_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='player1_name',
            new_name='user1_name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='player1_score',
            new_name='user1_score',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='player2_name',
            new_name='user2_name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='player2_score',
            new_name='user2_score',
        ),
        migrations.RemoveField(
            model_name='room',
            name='order_of_play',
        ),
        migrations.AddField(
            model_name='room',
            name='user1_player',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='user2_player',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
