# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards_db', '0003_auto_20160720_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
